### ISSUE TITLE
Input button extensions are not styled anymore

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-demo-app#98]
It seems that we're using an obsolete bootstrap syntax for input buttons. The `.input-group-addon` does not seem to work anymore and `.input-group-append` is used instead (see https://getbootstrap.com/docs/4.0/components/input-group/)

Occurrences: https://github.com/windingtree/wt-demo-app/search?utf8=%E2%9C%93&q=input-group-addon&type=

Be sure to base your work on `develop` branch.

**Comment by ganes1410** [comment]
I will do this @JirkaChadima

**Comment by ganes1410** [comment]
Hey @JirkaChadima . i have some trouble setting the project up

**Comment by JirkaChadima** [comment]
@ganes1410 If you checkout the develop branch, it should be enough to run `npm install` and `npm start` In master branch, there are still some issues (that we know of). Also we know, that node 8.9.4 and above work. We're not supporting older releases.

What kind of issues do you face?

**Comment by ganes1410** [comment]
@JirkaChadima  I get this when i run `npm start` and i am using node 9.8.0
```
  Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: Exceeds block gas limit
    at StateManager.queueTransaction (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/statemanager.js:291:21)
    at GethApiDouble.eth_sendTransaction (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:232:14)
    at GethApiDouble.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:61:10)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at SolcSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/solc.js:28:7)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at VmSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:40:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at GethDefaults.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:17:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at Object.InvalidResponse (/home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/ganesh/github/wt-demo-app/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

```

**Comment by JirkaChadima** [comment]
@ganes1410 Ahh, ok. Do you happen to have an existing instance of testrpc/other node running locally on port `8545`? If not, what version of `ethereumjs-testrpc` was installed in `node_modules`? And if yes, could you terminate it before running `npm start`?

**Comment by ganes1410** [comment]
@JirkaChadima   it was already running on  port 8545.now its working.
Should i change all occurences of `input-group-addon` because some are missing in the search results that you linked

**Comment by JirkaChadima** [comment]
@ganes1410 Cool, great to hear that! It would be amazing, if you could fix all occurrences, the search was just a rough example of what's going on. Thank you so much!
